name: Second workflow
on: push
jobs:
 test-project:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.1.1
   - name: Setup .NET
     uses: actions/setup-dotnet@v4.0.0
     with:
      dotnet-version: '8'
   - name: Setup Dependencies
     run: dotnet restore
   - name: Build
     run: dotnet build --no-restore
   - name: Print message
     run: echo "All is OK!"